[package]
name = "music_cluster_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.1.0"
filepath = "0.1.2"
lofty = "0.17.1"
